import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    padding: 16,
    fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
    color: "#eaeaea",
    background: "#0b0b0f",
    minHeight: "100vh",
  },
  title: { margin: "0 0 12px 0", fontSize: 18, fontWeight: 800 },
  transport: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    padding: 12,
    borderRadius: 14,
    border: "1px solid #222",
    background: "#12121a",
    width: "fit-content",
  },
  grid: {
    marginTop: 12,
    display: "grid",
    gridTemplateColumns: "1.3fr 1fr",
    gap: 12,
    alignItems: "start",
  },
  card: {
    border: "1px solid #222",
    borderRadius: 16,
    background: "#0f0f16",
    padding: 12,
  },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "start", marginBottom: 8 },
  cardTitle: { fontWeight: 800, fontSize: 14 },
  cardSub: { opacity: 0.7, fontSize: 12, marginTop: 2 },
  controls: {
    marginTop: 10,
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    alignItems: "center",
  },
  master: {
    marginTop: 12,
    padding: 12,
    display: "flex",
    gap: 12,
    alignItems: "center",
    borderRadius: 14,
    border: "1px solid #222",
    background: "#12121a",
    width: "fit-content",
  },
  button: {
    padding: "8px 12px",
    borderRadius: 12,
    border: "1px solid #2a2a38",
    background: "#1a1a26",
    color: "#fff",
    cursor: "pointer",
  },
  label: { display: "flex", alignItems: "center", gap: 10, fontSize: 12 },
  input: {
    width: 86,
    padding: "6px 8px",
    borderRadius: 10,
    border: "1px solid #2a2a38",
    background: "#0f0f16",
    color: "#fff",
  },
  dim: { opacity: 0.7, fontSize: 12 },
  note: { marginTop: 12, opacity: 0.75, fontSize: 12 },
};
